"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const NumTS_1 = require("../NumTS");
let a = [[1, 2]];
let b = [[2], [3]];
console.log(NumTS_1.NumTS.matrixDotProduct(a, b));
a = [[1, 2], [3, 4]];
b = [[5], [6]];
console.log(NumTS_1.NumTS.matrixDotProduct(a, b));
a = [[1, 2], [3, 4]];
b = [[5, 6], [7, 8]];
console.log(NumTS_1.NumTS.matrixDotProduct(a, b));
console.log(NumTS_1.NumTS.matrixSum(a, b));
console.log(NumTS_1.NumTS.matrixElemtWiseMult(a, b));
b = [[5], [6]];
console.log("transpose-------------");
console.log(NumTS_1.NumTS.matrixTransposse(a));
console.log(NumTS_1.NumTS.matrixTransposse(b));
b = [[5, 6]];
console.log(NumTS_1.NumTS.matrixTransposse(b));
b = [[6]];
console.log(NumTS_1.NumTS.matrixTransposse(b));
